### ISSUE TITLE
TableValuedParam - OperationalError when row with null attribute is followed by a row with non null attribute

### ISSUE THREAD

**Issue by davidhozic** [denisenkom/pytds#137] opened 2022-06-03 12:45 UTC
When using ` pytds.TableValuedParam` and `cursor.callproc`,
if a row with a null atrribute inside the table is folowed by a row with a non null value for the same attribute, the remote procedure call will return the following error:
```
OperationalError('The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Table-valued parameter 1 (""), row 6, column 2: Data type 0xE7 has an invalid data length or metadata length. The data for the table-valued parameter 6 doesn\'t conform to the table type of the parameter. SQL Server error is: 8037, state: 30')
```
This error is avoided if the non null attribute row appears before the null one

**Comment by takoau** [comment] 2022-12-19 06:15
@davidhozic Explanation as in https://github.com/denisenkom/pytds/issues/123.  Wordaround provided as well.

**Comment by denisenkom** [comment] 2023-08-27 23:13
Closing as duplicate of #123

**Closed by denisenkom** 2023-08-27 23:13 UTC
