### ISSUE TITLE
__name__ missed at getLogger in tds.py

### ISSUE THREAD

**Issue by ghost** [denisenkom/pytds#125] opened 2021-05-18 22:06 UTC
Current version of tds.py has that code on line 15

logger = logging.getLogger()

It is better to add '__name__' here, like that

logger = logging.getLogger(__name__)

Asking because I can change logging level for all modules in that package, except tds.py

logging.getLogger('pytds').setLevel(logging.ERROR)

**Comment by niconil** [comment] 2021-06-09 12:31
Duplicate of #117

**Comment by denisenkom** [comment] 2023-08-27 23:12
Closing since #117 was resolved

**Closed by denisenkom** 2023-08-27 23:12 UTC
